# harvested from https://github.com/ringcentral/vscode-openapi-linter/blob/687a00992fd6f8e1390d58fe05607637437e5767/server/src/.spectral.yml on 2026-10-09 — a Spectral ruleset published in the provider's own GitHub repository (ringcentral/vscode-openapi-linter); found by GitHub code search, fetched verbatim
x-method: harvested
x-stamped: 2026-10-09
x-source-url: https://github.com/ringcentral/vscode-openapi-linter/blob/687a00992fd6f8e1390d58fe05607637437e5767/server/src/.spectral.yml
extends: ["spectral:oas", "spectral:asyncapi"]
rules:
  ensure-paths-kebab-case:
    description: Paths must be in kebab-case.
    message: '{{description}} (lower case and separated with hyphens)'
    formats: [oas3]
    type: style
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9]+})+$"